name: Robot Framework CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  Run-Test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Clone automation repository
        run: git clone https://github.com/AnandAryaIndexnine/github_action_automation.git automation-scripts

      - uses: actions/cache@v2
        id: cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Install pip dependencies
        run: |
          pip install --upgrade pip
          pip install -r automation-scripts/requirements.txt

      - name: Run Test
        run: python -m robot --outputdir results automation-scripts/Test/login_test.robot

      - name: Run Robot Framework tests and generate report
        run: |
          echo "ROBOT_RC=$?" >> "$GITHUB_ENV"

      - name: Publish test results
        uses: actions/upload-artifact@v2
        with:
          name: robot-test-results
          path: results
